### ISSUE TITLE
How to build phonology.json (consonant , vowel , tone marke) with IPA?

### ISSUE THREAD

**Issue by wannaphongcom** [googlei18n/language-resources#14]
Can you give me some advice?

**Comment by pasindud** [comment]
For which language are you trying to create the phonology ?
Typically tones can be marked in the lexicon

Documentation on phonology.json can be found here [1]

Examples
- https://github.com/googlei18n/language-resources/blob/master/si/festvox/ipa_phonology.json
- https://github.com/googlei18n/language-resources/blob/master/jv/festvox/phonology.json
- https://github.com/googlei18n/language-resources/blob/master/su/festvox/phonology.json
- https://github.com/googlei18n/language-resources/blob/master/af/festvox/phonology.json


1 - https://github.com/googlei18n/language-resources/blob/master/docs/JSON_PHONOLOGY.md

**Comment by wannaphongcom** [comment]
@pasindud I went to create the phonology  for thai language.

**Comment by pasindud** [comment]
Do you have existing phoneme inventory in another format ?

**Comment by wannaphongcom** [comment]
No, I haven't. Now I'm wondering about the tone marks. How should I write tone marks in phonology.json?

**Comment by pasindud** [comment]
I think then you can add it to the lexicon.

**Comment by wannaphongcom** [comment]
@pasindud I writen't tone marks to "feature_types" or phonology.json. Yes or No ?

**Comment by pasindud** [comment]
Sure, you could do something like this

```
{
  "feature_types": [
    [ "consonant", "voicing", "place", "ctype"],
    ......... ,
    ["tone", "level"]
  ],

  "features": [
    [ "vc", "consonant", "vowel", "silence"],
    ........,
    [ "level", "1", "2", "3"]
  ],

  "phones": [
    [ "p", "consonant", ..... , "1"]
  ]

}
```

**Comment by wannaphongcom** [comment]
I'm not sure that it is correct.

```
{
  "feature_types": [
    [ "consonant", "voicing", "place", "ctype"],
    ......... ,
    ["tone", "level"]
  ],

  "features": [
    [ "vc", "consonant", "vowel","tone", "silence"],
    ........,
    [ "level", "1", "2", "3"]
  ],

  "phones": [
    ["k",  "consonant", "voiceless",    "velar",  "p"],
    [ "kʰ","tone","1"]
  ]

}
```

**Comment by pasindud** [comment]
Yea it was my mistake, Your one is right

**Comment by wannaphongcom** [comment]
Thank you.
