### ISSUE TITLE
Merlin integration with festival for Bengali language.

### ISSUE THREAD

**Issue by Rajan-sust** [googlei18n/language-resources#18]
@pasindud sir, how you trained the TTS Voice without merlin defined in (https://github.com/googlei18n/language-resources/blob/master/bn/festvox/README.md).

I'm not understanding how can I integrate merlin with festival. I also viewed (https://github.com/googlei18n/language-resources/blob/master/bn/merlin/README.md).

Thanks in advance.

**Comment by pasindud** [comment]
As you might know (festvox/festival) and merlin are two TTS engines. We can setup festvox independently but you need to have a festvox setup to run merlin.  Therefore you can train a festival voice first using this [1]. Then you can build a merlin voice using this [2], where you have to give the path to the festvox voice you built earlier.

1 - https://github.com/googlei18n/language-resources/blob/master/bn/festvox/README.md
2 - https://github.com/googlei18n/language-resources/blob/master/bn/merlin/README.md

**Comment by Rajan-sust** [comment]
Thanks for the reply, sir. If I trouble any problem, I will query again.

**Comment by Rajan-sust** [comment]
@pasindud sir, I trained merlin successfully with festival following the README.md [1]. Now, how can I synthesis speech for a particular sentence. Please , provide me the command.
1 - https://github.com/googlei18n/language-resources/blob/master/bn/merlin/README.md

**Comment by pasindud** [comment]
During training some test wavs are synthesized, you can find those paths in the merlin log. To synth arbitrary sentences you have to use a script similar to [1] (with some modifications, mainly to the file paths). Let me try to put together a small script with those modifications. Also refer to [2] for more info on our voice building process.

[1] - https://github.com/googlei18n/language-resources/blob/master/docker-images/test-merlin/synth.sh  

[2] - https://ai.google/research/pubs/pub47347

**Comment by Rajan-sust** [comment]
Thanks for the guideline @pasindud. Hope you will provide  modified script.

**Comment by pasindud** [comment]
Can you try this script [1], Change the variables  ```MERLIN_PATH``` and ```FESTIVAL_VOICE_PATH``` and 
then run 

```echo "অলিম্পিক ইন্ডাস্ট্রিজ জীবনকে সহজ করে তুলেছে" | synth.sh "audio_file_name_without_wav_extension"```

1 - https://gist.github.com/pasindud/c36dc0611e6bf8bee918a2863e6a0939

**Comment by Rajan-sust** [comment]
@pasindud Sir, it worked perfectly. I am really grateful to you for your collaboration.

**Comment by pasindud** [comment]
👍
