### ISSUE TITLE
how to build the *_depot.far in af/textnorm/{classifier,verbalizer}

### ISSUE THREAD

**Issue by lifeiteng** [googlei18n/language-resources#3]
Hi,
no grammar file for *_depot.far, Is it convenient to release these files?

**Comment by pasindud** [comment]
You can build all the far files by ```bazel build af/textnorm/...``` 

Details about af sparrowhawk 
https://github.com/googlei18n/language-resources/blob/master/af/sparrowhawk/README.md

**Comment by pasindud** [comment]
Releasing grammar files is currently not in our plan
