### ISSUE TITLE
unicode.fst model

### ISSUE THREAD

**Issue by nengine** [googlei18n/language-resources#5]
Please let me know how can I build unicode.fst model?  Many thanks.

**Comment by mjansche** [comment]
This is a prebuilt codepoint n-gram language model. It was built on the basis of Burmese text that is known to be mostly in proper Unicode encoding. You can train a similar, smaller model as follows:

```
bazel build -c opt //my:train-ngram-model

cat third_party/wikimedia/wp_my_* |
tr -s ' ' '\n' |
bazel-bin/my/train-ngram-model > my_unicode.fst
```

**Comment by nengine** [comment]
Thanks a lot.
