### ISSUE TITLE
Mark diphthongs in IPA transcription of Tamil

### ISSUE THREAD

**Issue by brawer** [googlei18n/language-resources#7]
FYI, in http://unicode.org/cldr/trac/changeset/13540 I’ve changed the CLDR version of the Tamil-to-IPA transcription to mark diphthongs, for example மும்பை to [mumbaɪ̯] instead of [mumbaɪ]. You might want to consider doing the same.

**Comment by pasindud** [comment]
:+1:  Commited the changes 
https://github.com/googlei18n/language-resources/commit/185337605da4818d228ed44c832bb8a9bef75e78
